# Site settings
title: Igor's Positive Computing Blog
email: idvorkin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Computers should make people feel good about themselves and thier world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: idvorkin
github_username:  idvorkin

# Build settings
markdown: kramdown
